### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dfm** [saigrain/pyspot#1]
Hi Suzanne,

I'm looking to simulate some rotation light curves for a project that I'm working on. Is this a good code to use? If so, can you license it? :-)

**Comment by saigrain** [comment]
done!

**Comment by saigrain** [comment]
Hi Dan

It could be what you need - it depends on your purpose. It is the code I
used to simulate the light curves in the Kepler rotation blind exercise
(Aigrain et al. 2015), but the repo only contains the bit of code that goes
from spot properties (positions, sizes, emergence times etc...) to light
curves. In that paper I used a different bit of code, originally written
(in IDL!) by Joe Llama, to generate the spot properties in the first place.
Joe is happy for me to share his "regions.pro" code that generates the spot
properties, so let me know if you want that.

If you just want to set up some simple spot properties and simulate
moderately realistic light curves, pyspot probably does what you need.
There are two modes, one which is very fast and ignores limb darkening and
the variation in the projection angle within the area of the spot, and one
which does account for these two effects properly using the formalism of
Dorren (1988), but is slower. The Dorren formalism assumes circular spots,
the shape of the spots doesn't matter in the simplified case. Neither
version checks for overlapping spots so you have to watch out for that if
you care.

The code isn't very user friendly at all but Ruth has experience using it,
or I'm very happy to answer questions. I've just licensed it as you asked.

Suzanne

**Comment by dfm** [comment]
Awesome. Thanks! I'll take a look at this and keep you posted. I think that "moderately realistic light curves" are all that I need for now so this should be perfect. Thanks again!
